# coding: utf-8

# flake8: noqa
"""
    Multilogin v2 Local API

    This API is intended to be used from version 5 of Multilogin for managing cloud saved browser profiles.   To start/stop browser profiles please use the [Multilogin v1 Local API](https://app.swaggerhub.com/apis/Multilogin/MultiloginLocalRestAPI/1.0). # Creating profiles To create a profile send a POST request to the /profile endpoint. The mandatory parameters are the name of the profile, operating system and type of browser. The rest of the fingerprint will be generated automatically, unless you specify more details.  Here is an example request to create a Mimic profile for windows with a proxy: <pre>{ <br>\"name\": \"testProfile\", <br>\"browser\": \"mimic\", <br>\"os\": \"win\", <br>\"network\": { <br>    \"proxy\": { <br>        \"type\": \"HTTP\", <br>        \"host\": \"192.168.1.1\", <br>        \"port\": \"1080\", <br>        \"username\": \"username\", <br>        \"password\": \"password\" <br>        } <br>    } <br>} </pre> # Groups Each group has an unique ID that can be assigned either during the creating of a profile or by updating a profile.  The default group ID is 00000000-0000-0000-0000-000000000000 for Unassigned  # noqa: E501

    OpenAPI spec version: v2-beta
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.audio_context import AudioContext
from swagger_client.models.canvas import Canvas
from swagger_client.models.custom_extensions import CustomExtensions
from swagger_client.models.fonts import Fonts
from swagger_client.models.geolocation import Geolocation
from swagger_client.models.inline_response200 import InlineResponse200
from swagger_client.models.inline_response2001 import InlineResponse2001
from swagger_client.models.media_devices import MediaDevices
from swagger_client.models.navigator import Navigator
from swagger_client.models.network import Network
from swagger_client.models.plugins import Plugins
from swagger_client.models.ports import Ports
from swagger_client.models.profile import Profile
from swagger_client.models.proxy_configuration import ProxyConfiguration
from swagger_client.models.storage import Storage
from swagger_client.models.timezone import Timezone
from swagger_client.models.update_profile_example import UpdateProfileExample
from swagger_client.models.update_profile_example_network import UpdateProfileExampleNetwork
from swagger_client.models.web_gl import WebGL
from swagger_client.models.web_gl_metadata import WebGLMetadata
from swagger_client.models.web_rtc import WebRTC
